// GAME CONSTANTS

const CONSTANTS = {
  TILE_SIZE: 40,
  GRAVITY: 0.6,
  MOVE_SPEED: 1.2,
  MAX_SPEED: 7,
  MAX_FALL_SPEED: 15,
  FRICTION: 0.8,
  JUMP_FORCE: -14,
  DASH_FORCE: 18,
  DASH_COOLDOWN: 60,
  DASH_DURATION: 10,
  GLITCH_THRESHOLD: 100,
};
