// GAME CONSTANTS

export const CONSTANTS = {
  TILE_SIZE: 40,
  GRAVITY: 1.2,
  MOVE_SPEED: 7,
  MAX_SPEED: 12,
  MAX_FALL_SPEED: 40,
  FRICTION: 0.85,
  JUMP_FORCE: -25,
  DASH_FORCE: 35,
  DASH_COOLDOWN: 40,
  DASH_DURATION: 10,
  GLITCH_THRESHOLD: 120,
};
